### PR TITLE
Update Typo

### PR DESCRIPTION
**Pull request by hrittikhere**
Hey,
Found a small typo and this PR fixes this. Thanks!

### CODE REVIEW

**Comment by killercoda-github** [comment]
thanks @hrittikhere !

**Comment by hrittikhere** [comment]
Welcome @killercoda-github! There's some open for contributors tag on the website. Is there any way I can help? Let me know how the approach should be and what kind of help are you looking :)

**Comment by wuestkamp** [comment]
Nice @hrittikhere !

If you like to help creating or changing scenarios for some technologies that's always welcome!
We'll add more docs about this soon. So far we have public profiles listed here: https://killercoda.com/areas
If you have another technology not yet listed you could ask for it to be added via [support](https://killercoda.com/support)

The process for this repo (vim) would be:

1) Fork this repository
2) Add your scenario idea to the list in this README and create a PR (optional)
3) Add your fork to your Killercoda account on [killercoda.com/creator/repository](https://killercoda.com/creator/repository) ([help](https://killercoda.com/creators/get-started))
4) Create or modify scenarios and test your changes ([docs](https://killercoda.com/creators)) ([examples](https://github.com/killercoda/scenario-examples))
5) Create a PR from your fork into this repository

**Comment by hrittikhere** [comment]
Thanks @wuestkamp :) Do you have public slack or discord where community members can discuss or maybe seek help while discussing updates?

**Comment by wuestkamp** [comment]
You can join https://killer.sh/r?d=slack channel #killercoda
Or if there are urgent issues better contact https://killercoda.com/support

**Pull request merged**
