### PR TITLE
Extending Vim section

### PR DESCRIPTION
**Pull request by talented**
I've updated "First Steps" and added "Basic Operations" katas in Vim section. My intention is to add more scenarios and hands-on tasks to make this section for a perfect place to master Vim. 

https://killercoda.com/a4d35c33-15a3-4675-b3a9-d8db795b57f4

### CODE REVIEW

**Comment by wuestkamp** [comment]
Really nice @talented !
I would suggest we split "Basic Operations" into two separate scenarios "Moving around with keyboard shortcuts" and "Search and Replace".
What you think?

**Comment by talented** [comment]
Yes, It would be easier to follow. I'll update it accordingly. It might be also good to  add some numbering to the scenarios, starting from 00 - First Steps, 01 - Moving around etc.?

**Comment by wuestkamp** [comment]
> I'll update it accordingly

thx!

I wouldn't go with numbering, but we can add a `structure.json` file to specify order like:

```
{
  "items": [
    { "path": "first-steps" },
    { "path": "moving-around" },
    { "path": "search-replace" },
    { "path": "cks-cka-ckad" }
  ]
}
```

**Comment by talented** [comment]
I've split the scenarios as discussed and defined the structure as you mentioned. Can you please have a look?

**Comment by wuestkamp** [comment]
Looking great! Thx!

I added your info as maintainer on https://killercoda.com/vim.
Let us know on https://killercoda.com/support whenever you want to change/remove it :)

**Comment by talented** [comment]
@wuestkamp thanks for adding me as a maintainer in Vim section. Challenge accepted! I'll be posting more comprehensive scenarios this week.

**Pull request merged**
